In [1]:
# from google.colab import drive
# drive.mount("/content/drive")

In [2]:
# !pip install pdfplumber -q
# !apt-get install ocrmypdf -q   #installing OCR library 

In [2]:
# import pdfplumber
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords 
from string import punctuation
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
from heapq import nlargest
from collections import defaultdict
import pandas as pd 
from nltk.collocations import *
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

In [4]:
# with pdfplumber.open("/content/drive/MyDrive/test.pdf") as pdf:
#     text=""
#     pages = pdf.pages
#     for page in pages:
#         text += page.extract_text(x_tolerance=2)
#         print(text)

# Import CV and scraped data

In [3]:
# Import CV
f=open('test.txt','r', errors = 'ignore')
text=f.read()

# Locations
f1=open('hk_districts.txt','r', errors = 'ignore')
text1=f1.read()
locations = word_tokenize(text1.replace("\n", " "))

# Additional stopwords
f2=open('stopwords.txt','r', errors = 'ignore')
text2=f2.read()
stopwords_additional = word_tokenize(text2.replace("\n", " "))

In [4]:
def nlp(x):
    word_sent = word_tokenize(x.lower().replace("\n",""))
    _stopwords = set(stopwords.words('english') + list(punctuation)+list("●")+list('–')+list('’')+locations+stopwords_additional)
    word_sent=[word for word in word_sent if word not in _stopwords]
    lemmatizer = WordNetLemmatizer()
    NLP_Processed_CV = [lemmatizer.lemmatize(word) for word in word_tokenize(" ".join(word_sent))]
#     return " ".join(NLP_Processed_CV)
    return NLP_Processed_CV

In [5]:
def get_key_word(x):
    finder = BigramCollocationFinder.from_words(x)
    lst = []
    Key_word_from_CV = []
    for i in sorted(finder.ngram_fd.items()):
    # if a double word appears more than once, then print it out.
        if i[1] > 1:
            print(i)
            lst.append(i[0])
        else:
            pass

    # print("************************")
    for j in lst:
    #     print(" ".join(j))
        Key_word_from_CV.append(" ".join(j))
    return Key_word_from_CV

In [6]:
NLP_Processed_CV = nlp(text)
# NLP_Processed_CV=' '.join(NLP_Processed_CV)
NLP_Processed_CV

['summarymotivated',
 'determined',
 'individual',
 'data',
 'science',
 'machine',
 'learning',
 'bootcamp',
 'experienced',
 'python',
 'data',
 'analysis',
 'machine',
 'learning',
 'multiple',
 'data',
 'science',
 'project',
 'background',
 'engineering',
 'enables',
 'develop',
 'logical',
 'analytical',
 'skill',
 'well',
 'recognizing',
 'teamwork',
 'effective',
 'communication',
 'currently',
 'seeking',
 'opportunity',
 'deploy',
 'data',
 'analytic',
 'skills.technical',
 'skill',
 'proficient',
 'python',
 'panda',
 'keras-tensorflow',
 'machine',
 'learning',
 'deep',
 'learning',
 'tableau',
 'familiar',
 'sqlxccelerate',
 'full-time',
 'data',
 'science',
 'machine',
 'learning',
 'immersive',
 'bootcamp',
 '03/2021',
 '07',
 '2021',
 'graduate',
 'xccelerate',
 'full-time',
 'data',
 'science',
 'bootcamp',
 'developing',
 'data',
 'science/',
 'machine',
 'learning',
 'project',
 'individually',
 'team',
 'project',
 'house',
 'ownership',
 'scheme',
 'market',
 'anal

In [7]:
key_word = get_key_word(NLP_Processed_CV)
key_word

(('data', 'science'), 4)
(('deep', 'learning'), 2)
(('electronic', 'component'), 2)
(('facial', 'detection'), 2)
(('full-time', 'data'), 2)
(('housing', 'estate'), 2)
(('machine', 'learning'), 6)
(('prediction', 'model'), 2)
(('price', 'prediction'), 2)
(('science', 'machine'), 2)


['data science',
 'deep learning',
 'electronic component',
 'facial detection',
 'full-time data',
 'housing estate',
 'machine learning',
 'prediction model',
 'price prediction',
 'science machine']

In [5]:
# print(NLP_Processed_CV)
# print(key_word)
df.shape

(20137, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20137 entries, 0 to 20136
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        20137 non-null  int64 
 1   JobID             20137 non-null  int64 
 2   title             20136 non-null  object
 3   company           20137 non-null  object
 4   location          15971 non-null  object
 5   salary            20137 non-null  object
 6   post_date         20137 non-null  object
 7   job highlights    20068 non-null  object
 8   job description   20137 non-null  object
 9   company overview  16740 non-null  object
 10  career level      20137 non-null  object
 11  qualification     14122 non-null  object
 12  experience        11576 non-null  object
 13  job type          20137 non-null  object
 14  industry          20137 non-null  object
 15  benefit           12913 non-null  object
 16  webpage           20137 non-null  object
 17  sal_low     

In [3]:
#Import scraped data
df = pd.read_csv("whole-v7-nlp.csv")
df.head(2)

Unnamed: 0  JobID                   title  \
0           0      0    Assistant IT Manager   
1           1      1  Finance and IT Manager   

                               company     location salary  \
0                        Wang On Group  Kowloon Bay      0   
1  Abdoolally Ebrahim Services Limited    Kwun Tong      0   

            post_date                                     job highlights  \
0  Posted 2 hours ago  Responsible for stability performance security...   
1  Posted 3 hours ago  Responsible for the finance and IT operations,...   

                                     job description  \
0  Responsibilities:Analyze business requirements...   
1  ResponsibilitiesFinanceResponsible for the fin...   

                                    company overview career level  \
0  \nWang On Group\n\nWang On Group (Stock Code: ...       Middle   
1  Abdoolally Ebrahim Group started its business ...       Senior   

  qualification experience              job type  \
0        Degree    8 years  Full Time, Permanent   
1        Degree    5 years  Full Time, Permanent   

                         industry  \
0  Management Consultancy/Service   
1        Trading and Distribution   

                                             benefit  \
0  Education allowance, Free shuttle bus, Life in...   
1  Double pay, Education allowance, Medical insur...   

                                             webpage  sal_low  sal_high  \
0  https://hk.jobsdb.com/hk/en/job/assistant-it-m...        0         0   
1  https://hk.jobsdb.com/hk/en/job/finance-and-it...        0         0   

                                                 All  
0  ['assistant manager wang group responsible sta...  
1  ['finance manager abdoolally ebrahim service l...

In [14]:
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.feature_extraction.text import TfidfVectorizer
# tfidf_vectorizer = TfidfVectorizer(stop_words='english')
# tfidf_jobid = tfidf_vectorizer.fit_transform(df['All'])
# # print(tfidf_jobid)
# user_tfidf = tfidf_vectorizer.transform(df2['All'])

In [15]:
# cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)
# output2 = list(cos_similarity_tfidf)
# output2

In [16]:
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.feature_extraction.text import TfidfVectorizer
# def TFIDF(scraped_data, cv):
#     tfidf_vectorizer = TfidfVectorizer(stop_words='english')

#     # TF-IDF Scraped data
#     tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

#     # TF-IDF CV
#     user_tfidf = tfidf_vectorizer.transform(cv)

#     # Using cosine_similarity on (Scraped data) & (CV)
#     cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

#     output2 = list(cos_similarity_tfidf)
#     return output2
    
# output2 = TFIDF(df['All'], df2['All'])
# output2

# Put keyword/CV into a dataframe

In [11]:
df2 = pd.DataFrame()
# append columns to an empty DataFrame
df2['title'] = ["I"]
df2['job highlights'] = ["I"]
df2['job description'] = ["I"]
df2['company overview'] = ["I"]
df2['industry'] = ["I"]

# Compare with the key words from CV only
df2['All'] = " ".join(key_word)

# Compare with the entire CV
# df2['All'] = " ".join(NLP_Processed_CV)
# df2

# Create get_recommendation function

In [12]:
def get_recommendation(top, df_all, scores):
    recommendation = pd.DataFrame(columns = ['JobID',  'title', 'industry', 'job description','score'])
    count = 0
    for i in top:
#         recommendation.at[count, 'ApplicantID'] = u
        recommendation.at[count, 'JobID'] = df.index[i]
        recommendation.at[count, 'title'] = df['title'][i]
        recommendation.at[count, 'industry'] = df['industry'][i]
#         recommendation.at[count, 'location'] = df['location'][i]
        recommendation.at[count, 'job description'] = df['job description'][i]
        recommendation.at[count, 'score'] =  scores[count]
        count += 1
    return recommendation

# TFIDF

In [13]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def TFIDF(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # TF-IDF Scraped data
    tfidf_jobid = tfidf_vectorizer.fit_transform(scraped_data)

    # TF-IDF CV
    user_tfidf = tfidf_vectorizer.transform(cv)

    # Using cosine_similarity on (Scraped data) & (CV)
    cos_similarity_tfidf = map(lambda x: cosine_similarity(user_tfidf,x),tfidf_jobid)

    output2 = list(cos_similarity_tfidf)
    return output2
    
output2 = TFIDF(df['All'], df2['All'])
output2

[array([[0.01004203]]),
 array([[0.00277372]]),
 array([[0.01380723]]),
 array([[0.0042945]]),
 array([[0.01483838]]),
 array([[0.00927136]]),
 array([[0.]]),
 array([[0.0074321]]),
 array([[0.02078868]]),
 array([[0.00356108]]),
 array([[0.00450561]]),
 array([[0.00479991]]),
 array([[0.00466231]]),
 array([[0.]]),
 array([[0.00863563]]),
 array([[0.00862199]]),
 array([[0.00314284]]),
 array([[0.00507078]]),
 array([[0.01038314]]),
 array([[0.02121474]]),
 array([[0.01357133]]),
 array([[0.00945792]]),
 array([[0.02001338]]),
 array([[0.0120537]]),
 array([[0.02072318]]),
 array([[0.]]),
 array([[0.02679346]]),
 array([[0.00785341]]),
 array([[0.01091518]]),
 array([[0.01496459]]),
 array([[0.02635305]]),
 array([[0.00349383]]),
 array([[0.03310537]]),
 array([[0.01452733]]),
 array([[0.02757567]]),
 array([[0.00277911]]),
 array([[0.00247154]]),
 array([[0.]]),
 array([[0.00420295]]),
 array([[0.02411737]]),
 array([[0.02654077]]),
 array([[0.00298215]]),
 array([[0.01891538]]),
 ar

In [14]:
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:100]
list_scores = [output2[i][0][0] for i in top]
TF=get_recommendation(top,df, list_scores)
TF

JobID                                              title  \
0     600  Senior Data Scientist/Machine Learning Enginee...   
1     641  Senior Machine Learning Engineer/Expert (Plann...   
2    3942               Software Engineer Trainee (AI / GIS)   
3   12794  Vice President, Big Data Analytics & Machine L...   
4    7357  Associate Data Scientist/ Data Scientist - Top...   
..    ...                                                ...   
95  14851             SENIOR ESTATE MANAGER / ESTATE MANAGER   
96   7276  Chief Data Architect - MNC, Digital Transforma...   
97   7374                                     Data Scientist   
98   3109     Director - Artificial Intelligence (AI) & Data   
99   2546  (Senior) Data Engineer | Multiple Openings | P...   

                                  industry  \
0                   Information Technology   
1                   Information Technology   
2                                   Others   
3                       Financial Services   
4   Human Resources Management/Consultancy   
..                                     ...   
95       Property Management / Consultancy   
96  Human Resources Management/Consultancy   
97                  Information Technology   
98  Human Resources Management/Consultancy   
99  Human Resources Management/Consultancy   

                                      job description     score  
0   Job Responsibilities:•Responsible for the algo...  0.308117  
1   Job Responsibilities:•Responsible for the algo...  0.291789  
2   To participate in several large-scale Artifici...  0.281831  
3   Responsibilities:Explore the availability, acc...  0.255755  
4   Junior Data Scientist focused on machine learn...  0.255316  
..                                                ...       ...  
95  Responsibilities Overall monitoring a team of ...  0.125781  
96  About the ClientOur client is well established...  0.125771  
97  Job Responsibilities:Develop and implement Mac...  0.125029  
98  Our Client:Our client is a conglomerate group ...  0.124013  
99  Data Engineer | FSI | Perm | 40 - 48kDuties:Re...  0.121537  

[100 rows x 5 columns]

# Count Vectorizer

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def count_vectorize(scraped_data, cv):
    # CountV the scraped data
    count_vectorizer = CountVectorizer()
    count_jobid = count_vectorizer.fit_transform(scraped_data) #fitting and transforming the vector

    # CountV the cv
    user_count = count_vectorizer.transform(cv)
    cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
    output3 = list(cos_similarity_countv)
    return output3
output3 = count_vectorize(df['All'], df2['All'])
output3

[array([[0.03279129]]),
 array([[0.0151255]]),
 array([[0.04519045]]),
 array([[0.03608178]]),
 array([[0.07871211]]),
 array([[0.03961453]]),
 array([[0.]]),
 array([[0.02699992]]),
 array([[0.09709831]]),
 array([[0.03507393]]),
 array([[0.0192281]]),
 array([[0.0295519]]),
 array([[0.01495413]]),
 array([[0.]]),
 array([[0.03435365]]),
 array([[0.03141437]]),
 array([[0.02201542]]),
 array([[0.02848725]]),
 array([[0.01609661]]),
 array([[0.02789883]]),
 array([[0.04364098]]),
 array([[0.03802288]]),
 array([[0.03926796]]),
 array([[0.03261062]]),
 array([[0.05052016]]),
 array([[0.]]),
 array([[0.08780925]]),
 array([[0.01845141]]),
 array([[0.0547791]]),
 array([[0.03798247]]),
 array([[0.12673854]]),
 array([[0.01756956]]),
 array([[0.05011563]]),
 array([[0.02339501]]),
 array([[0.05317546]]),
 array([[0.01197369]]),
 array([[0.03587624]]),
 array([[0.]]),
 array([[0.03772466]]),
 array([[0.07878084]]),
 array([[0.15580264]]),
 array([[0.02913583]]),
 array([[0.04883009]]),
 arr

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

count_vectorizer = CountVectorizer()
count_jobid = count_vectorizer.fit_transform(df['All']) #fitting and transforming the vector
count_jobid


<20137x144460 sparse matrix of type '<class 'numpy.int64'>'
	with 2913905 stored elements in Compressed Sparse Row format>

In [38]:
# print(count_jobid)

In [17]:
user_count = count_vectorizer.transform(df2['All'])
user_count

<1x144460 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [39]:
print(user_count)

  (0, 319)	1
  (0, 341)	1
  (0, 426)	3
  (0, 465)	2
  (0, 547)	2
  (0, 726)	1
  (0, 1620)	1
  (0, 1630)	2
  (0, 1641)	2
  (0, 1659)	1
  (0, 1713)	2
  (0, 5024)	1
  (0, 5219)	1
  (0, 5262)	1
  (0, 6712)	1
  (0, 9721)	3
  (0, 10005)	1
  (0, 10006)	1
  (0, 10107)	1
  (0, 12424)	1
  (0, 13076)	1
  (0, 14287)	1
  (0, 14310)	1
  (0, 15754)	1
  (0, 16326)	3
  :	:
  (0, 88743)	2
  (0, 88882)	1
  (0, 89694)	1
  (0, 94758)	1
  (0, 95328)	1
  (0, 96077)	1
  (0, 96687)	1
  (0, 96745)	1
  (0, 96754)	2
  (0, 96773)	3
  (0, 97411)	1
  (0, 97538)	1
  (0, 98163)	1
  (0, 98230)	2
  (0, 98806)	1
  (0, 99413)	1
  (0, 101197)	1
  (0, 102115)	1
  (0, 102946)	1
  (0, 102954)	1
  (0, 103660)	2
  (0, 103733)	1
  (0, 104226)	1
  (0, 104810)	1
  (0, 105680)	1


In [36]:
cos_similarity_countv = map(lambda x: cosine_similarity(user_count, x),count_jobid)
output3 = list(cos_similarity_countv)
output3

[array([[0.10606602]]),
 array([[0.07429292]]),
 array([[0.10363524]]),
 array([[0.09509652]]),
 array([[0.14401646]]),
 array([[0.08542422]]),
 array([[0.07074606]]),
 array([[0.06145682]]),
 array([[0.17977193]]),
 array([[0.06442805]]),
 array([[0.05067726]]),
 array([[0.08496707]]),
 array([[0.06091078]]),
 array([[0.06979961]]),
 array([[0.10974773]]),
 array([[0.09032199]]),
 array([[0.13538808]]),
 array([[0.05460401]]),
 array([[0.07713446]]),
 array([[0.10249591]]),
 array([[0.0705801]]),
 array([[0.08199201]]),
 array([[0.10537566]]),
 array([[0.08073902]]),
 array([[0.10490611]]),
 array([[0.06454972]]),
 array([[0.14126158]]),
 array([[0.07957672]]),
 array([[0.12906237]]),
 array([[0.07098422]]),
 array([[0.15735293]]),
 array([[0.10734582]]),
 array([[0.07054481]]),
 array([[0.08548248]]),
 array([[0.08372498]]),
 array([[0.05881197]]),
 array([[0.07521405]]),
 array([[0.09883773]]),
 array([[0.09038769]]),
 array([[0.11954652]]),
 array([[0.16922964]]),
 array([[0.079116

In [ ]:
# output3 = count_vectorize(df['All'], df2['All'])
# output3

In [18]:
top = sorted(range(len(output3)), key=lambda i: output3[i], reverse=True)[:100]
list_scores = [output3[i][0][0] for i in top]
cv=get_recommendation(top, df, list_scores)
cv

JobID                                              title  \
0   1402                              Senior Data Scientist   
1   6868                                     Data Scientist   
2   3942               Software Engineer Trainee (AI / GIS)   
3   7259  Data Insights Analyst (Big Data- Machine Learn...   
4   7582                           Data Scientist Team Lead   
..   ...                                                ...   
95  3997                                      Data Engineer   
96  7347                   Manager, Data Quality Management   
97  7567                     Data Architect / Data Engineer   
98   936  3 headcounts (AM/ Manager/ Sr Manager) Data Go...   
99  7474  Data Analyst/ Assistant Manager, Core Banking ...   

                                  industry  \
0                       Financial Services   
1                       Financial Services   
2                                   Others   
3   Human Resources Management/Consultancy   
4   Human Resources Management/Consultancy   
..                                     ...   
95                  Information Technology   
96                      Financial Services   
97                       Telecommunication   
98  Human Resources Management/Consultancy   
99                      Financial Services   

                                      job description     score  
0   HASE Data OfficeThe Data Office of Hang Seng i...  0.449485  
1   Your key responsibilitiesPerform data analysis...  0.421066  
2   To participate in several large-scale Artifici...  0.420887  
3   RESPONSIBILITIESPerform data analysis and prov...  0.420814  
4   A top tier bank in Hk is hirirng for a data sc...  0.411256  
..                                                ...       ...  
95  Job ResponsibilitiesWork closely with business...  0.278737  
96  Reporting to the Section Head - Data Quality M...  0.278429  
97  OpportunitiesJoin us on an exciting venture to...  0.278214  
98  Job Title:      AM/ Manager/ Sr Manager - Data...  0.277255  
99  Reporting to the Project Manager / Head of Dat...  0.277005  

[100 rows x 5 columns]

# KNN

In [19]:
from sklearn.neighbors import NearestNeighbors

def KNN(scraped_data, cv):
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    n_neighbors = 100
    KNN = NearestNeighbors(n_neighbors, p=2)
    KNN.fit(tfidf_vectorizer.fit_transform(scraped_data))
#     NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv), return_distance=True)
    NNs = KNN.kneighbors(tfidf_vectorizer.transform(cv))
    top = NNs[1][0][1:]
    index_score = NNs[0][0][1:]

    knn = get_recommendation(top, df, index_score)
    return knn

knn = KNN(df['All'], df2['All'])
knn

/Users/CooperLiPC/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:68: FutureWarning: Pass n_neighbors=100 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


JobID                                              title  \
0     641  Senior Machine Learning Engineer/Expert (Plann...   
1    3942               Software Engineer Trainee (AI / GIS)   
2   12794  Vice President, Big Data Analytics & Machine L...   
3    7357  Associate Data Scientist/ Data Scientist - Top...   
4    3247          Machine Learning Engineer/ Data Scientist   
..    ...                                                ...   
94  14851             SENIOR ESTATE MANAGER / ESTATE MANAGER   
95   7276  Chief Data Architect - MNC, Digital Transforma...   
96   7374                                     Data Scientist   
97   3109     Director - Artificial Intelligence (AI) & Data   
98   2546  (Senior) Data Engineer | Multiple Openings | P...   

                                  industry  \
0                   Information Technology   
1                                   Others   
2                       Financial Services   
3   Human Resources Management/Consultancy   
4                        Telecommunication   
..                                     ...   
94       Property Management / Consultancy   
95  Human Resources Management/Consultancy   
96                  Information Technology   
97  Human Resources Management/Consultancy   
98  Human Resources Management/Consultancy   

                                      job description    score  
0   Job Responsibilities:•Responsible for the algo...  1.19014  
1   To participate in several large-scale Artifici...  1.19847  
2   Responsibilities:Explore the availability, acc...  1.22004  
3   Junior Data Scientist focused on machine learn...   1.2204  
4   Machine Learning Engineer/ Data ScientistOppor...  1.23118  
..                                                ...      ...  
94  Responsibilities Overall monitoring a team of ...  1.32229  
95  About the ClientOur client is well established...  1.32229  
96  Job Responsibilities:Develop and implement Mac...  1.32285  
97  Our Client:Our client is a conglomerate group ...  1.32362  
98  Data Engineer | FSI | Perm | 40 - 48kDuties:Re...  1.32549  

[99 rows x 5 columns]

In [24]:
knn.to_csv('knn.csv', index=False)

# Combined TFIDF, CV and KNN result together, to make a dataframe "final"

In [20]:
# merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
# final = merge1.merge(cv[['JobID','score']], on = "JobID")
# final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
# final.head()

merge1 = knn[['JobID','title', 'score']].merge(TF[['JobID','score']], on= "JobID")
final = merge1.merge(cv[['JobID','score']], on = "JobID")
final = final.rename(columns={"score_x": "KNN", "score_y": "TF-IDF","score": "CV"})
final.head()

JobID                                              title      KNN  \
0    641  Senior Machine Learning Engineer/Expert (Plann...  1.19014   
1   3942               Software Engineer Trainee (AI / GIS)  1.19847   
2  12794  Vice President, Big Data Analytics & Machine L...  1.22004   
3   7357  Associate Data Scientist/ Data Scientist - Top...   1.2204   
4   3247          Machine Learning Engineer/ Data Scientist  1.23118   

     TF-IDF        CV  
0  0.291789  0.364723  
1  0.281831  0.420887  
2  0.255755  0.360825  
3  0.255316  0.403841  
4  0.242092  0.410141

In [26]:
# high = max(knn['score'])
# def reverseScoring(df, high, cols):
#     '''Reverse scores on given columns
#      df = your data frame,
#      high = highest score available
#      cols = the columns you want reversed in list form'''
#     df[cols] = high - df[cols]
# #     return df['score']
#     return df
# reverseScoring(knn, high, 'score')

In [27]:
# reverseScoring(knn, high, 'score').to_csv('test.csv', index=False)

# Scale and assign weights

In [28]:
# Scale it
from sklearn.preprocessing import MinMaxScaler
slr = MinMaxScaler()
final[["KNN", "TF-IDF", 'CV']] = slr.fit_transform(final[["KNN", "TF-IDF", 'CV']])

# Multiply by weights
final['KNN'] = (1-final['KNN'])/3
final['TF-IDF'] = final['TF-IDF']/3
final['CV'] = final['CV']/3
final['Final'] = final['KNN']+final['TF-IDF']+final['CV']
final.sort_values(by="Final", ascending=False)

JobID                                              title         KNN  \
0    641  Senior Machine Learning Engineer/Expert (Plann...    0.333333   
3   7357  Associate Data Scientist/ Data Scientist - Top...     0.27341   
7   7259  Data Insights Analyst (Big Data- Machine Learn...    0.249845   
2   3942               Software Engineer Trainee (AI / GIS)    0.275054   
10   857                           Associate Data Scientist    0.214888   
..   ...                                                ...         ...   
52   885       Programmer, Machine Learning/ AI development   0.0270944   
48  1844               Software / Machine Learning Engineer   0.0403543   
59  7603         Data Scientist - Leading Bank in Hong Kong  0.00491511   
56  5566  Senior Consultant / Manager, Data Scientist, D...   0.0194597   
60  1157           Data Scientist / Computational Scientist           0   

        TF-IDF           CV       Final  
0     0.333333     0.189947    0.856614  
3     0.275167     0.278731    0.827308  
7     0.252081     0.325352    0.827278  
2     0.276773     0.248643     0.80047  
10    0.217617     0.310602    0.743106  
..         ...          ...         ...  
52    0.027984    0.0508848    0.105963  
48   0.0416218   0.00386648   0.0858426  
59  0.00508816    0.0321145   0.0421177  
56   0.0201146  0.000522725    0.040097  
60           0   0.00414767  0.00414767  

[61 rows x 6 columns]

In [29]:
# final.to_csv('final.csv', index=False)
final2 = final.sort_values(by="Final", ascending=False).copy()
final2

JobID                                              title         KNN  \
0    641  Senior Machine Learning Engineer/Expert (Plann...    0.333333   
3   7357  Associate Data Scientist/ Data Scientist - Top...     0.27341   
7   7259  Data Insights Analyst (Big Data- Machine Learn...    0.249845   
2   3942               Software Engineer Trainee (AI / GIS)    0.275054   
10   857                           Associate Data Scientist    0.214888   
..   ...                                                ...         ...   
52   885       Programmer, Machine Learning/ AI development   0.0270944   
48  1844               Software / Machine Learning Engineer   0.0403543   
59  7603         Data Scientist - Leading Bank in Hong Kong  0.00491511   
56  5566  Senior Consultant / Manager, Data Scientist, D...   0.0194597   
60  1157           Data Scientist / Computational Scientist           0   

        TF-IDF           CV       Final  
0     0.333333     0.189947    0.856614  
3     0.275167     0.278731    0.827308  
7     0.252081     0.325352    0.827278  
2     0.276773     0.248643     0.80047  
10    0.217617     0.310602    0.743106  
..         ...          ...         ...  
52    0.027984    0.0508848    0.105963  
48   0.0416218   0.00386648   0.0858426  
59  0.00508816    0.0321145   0.0421177  
56   0.0201146  0.000522725    0.040097  
60           0   0.00414767  0.00414767  

[61 rows x 6 columns]

In [30]:
final2.head(10)

JobID                                              title       KNN  \
0     641  Senior Machine Learning Engineer/Expert (Plann...  0.333333   
3    7357  Associate Data Scientist/ Data Scientist - Top...   0.27341   
7    7259  Data Insights Analyst (Big Data- Machine Learn...  0.249845   
2    3942               Software Engineer Trainee (AI / GIS)  0.275054   
10    857                           Associate Data Scientist  0.214888   
8    7312          Artificial Intelligence (AI) R&D Engineer  0.242279   
9    5717  Data Science Manager - Machine Learning/AI | 2...  0.239048   
4   12794  Vice President, Big Data Analytics & Machine L...  0.270547   
12   3247          Machine Learning Engineer/ Data Scientist   0.19946   
14   7582                           Data Scientist Team Lead  0.178896   

      TF-IDF        CV     Final  
0   0.333333  0.189947  0.856614  
3   0.275167  0.278731  0.827308  
7   0.252081  0.325352  0.827278  
2   0.276773  0.248643   0.80047  
10  0.217617  0.310602  0.743106  
8   0.244644  0.238304  0.725226  
9   0.241464  0.212282  0.692794  
4   0.272368  0.142904  0.685819  
12  0.202323  0.259108   0.66089  
14  0.181858  0.299642  0.660395

In [31]:
# final2.merge(df, on="JobID")
final_salary = df.merge(final2, on="JobID")
final_salary

Unnamed: 0  JobID                                            title_x  \
0          285    285                      Data Analyst (System Analyst)   
1          298    298                                     Data Scientist   
2          352    352                                       Data Analyst   
3          429    429  Data Science Intern (6-9 months contract from ...   
4          641    641  Senior Machine Learning Engineer/Expert (Plann...   
..         ...    ...                                                ...   
56        7582   7582                           Data Scientist Team Lead   
57        7603   7603         Data Scientist - Leading Bank in Hong Kong   
58       10911  10911  Manager and Strategic Lead, Learning Analytics...   
59       12794  12794  Vice President, Big Data Analytics & Machine L...   
60       13897  13897  CIB Global Research - Applied AI & Machine Lea...   

                                              company            location  \
0     China Life Insurance (Overseas) Company Limited            Hung Hom   
1                                                Arup        Kowloon City   
2   China State Construction Engineering (Hong Kon...            Wan Chai   
3                                       AXA Hong Kong       Southern Area   
4     TCL Corporate Research (Hong Kong) Co., Limited         Shatin Area   
..                                                ...                 ...   
56                        Cornerstone Global Partners  Yau Tsim Mong Area   
57                                       Michael Page                 NaN   
58                                 Lingnan University       Tuen Mun Area   
59  China Construction Bank (Asia) Corporation Lim...                 NaN   
60                          JPMorgan Chase Bank, N.A.                 NaN   

   salary            post_date  \
0       0   Posted 4 hours ago   
1       0  Posted on 14-Jul-21   
2       0  Posted on 13-Jul-21   
3       0  Posted on 14-Jul-21   
4       0  Posted 21 hours ago   
..    ...                  ...   
56      0  Posted on 17-Jun-21   
57      0  Posted on 16-Jun-21   
58      0  Posted on 23-Jun-21   
59      0  Posted on 13-Jul-21   
60      0   Posted on 8-Jul-21   

                                       job highlights  \
0   SQL, Python, Tableau/Congo’s, Machine Learning...   
1   Degree in Mathematics, Data Science or related...   
2   Degree holder with 3 year's big data analysis ...   
3   Exposure to Life Insurance Data Science, Full-...   
4   reinforcement learning, Postdoc, deep learning...   
..                                                ...   
56                 team lead, data scientist, finance   
57  Permanent Headcount, New Data Initiatives, Pre...   
58  work across the University to leverage data, l...   
59        Data Management, Big Data, Machine Learning   
60  Minimum 6 years experience in a data analytics...   

                                      job description  \
0   Responsibilities:Perform data architecture, da...   
1   Responsibilities:Create, develop and maintain ...   
2   Job Description:Develop reference modules and ...   
3   Career OpportunitiesLearn to solve real busine...   
4   Job Responsibilities:•Responsible for the algo...   
..                                                ...   
56  A top tier bank in Hk is hirirng for a data sc...   
57  The Data Scientist will sit in the centralised...   
58  Lingnan University, a distinctive liberal arts...   
59  Responsibilities:Explore the availability, acc...   
60  Data Analytics at JPMorgan Corporate Investmen...   

                                     company overview  ...  \
0   China Life Insurance (Overseas) Company Limite...  ...   
1   Arup is the creative force at the heart of man...  ...   
2   We are a listed group with diversified interes...  ...   
3   ABOUT AXA HONG KONG\n\nAXA Hong Kong, a member...  ...   
4   TCL is one of the world’s leading manufacturer...  ...   
..             